### ISSUE TITLE
PERLU PERBAIKI Sevima Training Meetup #1

### ISSUE THREAD

**Issue by GarryLaly** [sylkirian/todolist#1]
Terima kasih atas effort mengerjakan task di meetup #1

Hasil review:
- Kode sudah rapi
- Penggunaan komponen tidak tepat, bahkan tidak ada
- Penamaan variable/method/file ada yang tidak sesuai dengan ketentuan dalam penamaan bahasa inggris

Komentar review yang perlu diperbaiki ada di https://github.com/sylkirian/todolist/commit/5de97823007d928706e089812ad0e4dbd793401f

Status:
Perlu diperbaiki agar dapat lolos

**Comment by sylkirian** [comment]
Ya waktu itu sih asal jadi mas, hehehe, tidak tahu kalau bakal direview sampai segininya :D. Ya mas, nanti dicoba diperbaiki.

**Comment by sylkirian** [comment]
Sudah diperbaiki mas, silakan dicek lagi jika berkenan
